### ISSUE TITLE
Users should be dereferencable

### ISSUE THREAD

**Issue by pietercolpaert** [pietercolpaert/linda#1]
Make sure users have a URI.

How:
1. In the admin interface, ask whether they have a URI for the user.
   - **yes**: try to dereference the URI and get a foaf:name, rdfs:label or schema:name from what you retrieve
   - **no**: ask for a name and create a URI ourself: {baseuri}/user/{name} which gives a 303 to {baseuri}/user/{name}.ttl or {baseuri}/user/{name}.html based on content negotiation

**Comment by pietercolpaert** [comment]
In each case: how it's done right now is not perfect: dct:creator should have a URI, not a xsd:string :)

**Comment by coreation** [comment]
Name is put into the {baseuri}/user/{name} schema. The first option seems a little excessive at the moment, but I get how this would be great to have. Will focus on the more relevant issues atm.

**Comment by pietercolpaert** [comment]
ack

**Comment by coreation** [comment]
@pietercolpaert  In the light of issue #30, how does this behave?

**Comment by pietercolpaert** [comment]
Create a blank node instead... easier

**Comment by coreation** [comment]
Currently we have baseuri/organization/{unique ID}#agent. Thinking this is a better approach then just using the name which isn't guaranteed to be unique? If this is ok, I think this issue is already resolved.

**Comment by pietercolpaert** [comment]
We are both talking about the e.g., contributor or creator of a dcat:CatalogRecord, right?

**Comment by coreation** [comment]
Aha, so users are (admin) users, not users you create using the admin (which are now organizations).(?) Hence my  reference to issue #30 where the users become organizations.

**Comment by pietercolpaert** [comment]
Indeed!

**Comment by coreation** [comment]
All of the users are now being added as proper resources and are dereferencable. Also fixed a small bug where there could only be 1 contributor (the last one), multiple are being added now. This took me quite a while because of [this](https://github.com/njh/easyrdf/issues/245) issue.
