### ISSUE TITLE
Distribution fields

### ISSUE THREAD

**Issue by pietercolpaert** [pietercolpaert/linda#24]
Distribution fields should be: 
- title
- downloadUrl
- accessUrl
- license

Use cases can thus be dropped.

**Comment by pietercolpaert** [comment]
Almost done: needs some debugging by @coreation

**Comment by coreation** [comment]
Small note, make sure the accessUrl and DownloadUrl are fully compliant URL's. Meaning they should have the scheme as well -> http(s).

**Comment by pietercolpaert** [comment]
The URIs for downloadURL and access URL are apperently these (!! not dcterms!!):

dcat:accessURL
dcat:downloadURL

**Comment by coreation** [comment]
Should be ok now, if confirmed, close the issue @pietercolpaert ;)
